### ISSUE TITLE
Catalog page not showing all components at the first time

### ISSUE THREAD

**Issue by gustavolira** [janus-idp/backstage-showcase#817] opened 2023-11-23 18:34 UTC
### Describe the bug

Go to the catalog page, by default `kind=compnent` will be used as default, not all components will be showed at the first time, to see all components you need to change `kind=api` for example and them select again `kind=component`

### Expected Behavior

Open Catalog page and see all components without need to interact with the page

### Versions of software used and environment
RHDH Helm Chart  1.0-190-CI
Platform: OpenShift version4.13.19

**Comment by Zaperex** [comment] 2023-11-23 20:53
@gustavolira Can I ask what you mean by not everything is shown? Is the title of your initial table of components `Owned Components` similar to this? If so, then this is expected since the default is to show all components owned by your backstage identity.
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/497d20db-f2c9-42fe-8bc2-fe6d226c68f3)
To view all the components, just press the `All` button in the filters:
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/704523b2-9e7b-4a7b-8daa-0b1e050b7823)
This should then show `All Components`:
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/1ddbcceb-8822-4cd4-b849-bced7bc62f89)

**Comment by gustavolira** [comment] 2023-11-23 22:40
@Zaperex 
Just hitting the page
![image](https://github.com/janus-idp/backstage-showcase/assets/1463004/053a7ef8-5f5d-454b-b9de-97bc9d12055a)

Changing the kind to another type and setting back kind = componentn

![image](https://github.com/janus-idp/backstage-showcase/assets/1463004/c4c88be6-5c88-43b4-be15-186fb25846d1)
"Changing the 'kind' to a different type and then resetting it to 'kind = componentn'."

**Comment by Zaperex** [comment] 2023-11-23 22:44
Yes it says all=3 but the default filter is for owned components which in your case has 1 component. To view all you just need to select the all filter

**Comment by gustavolira** [comment] 2023-11-23 22:44
@Zaperex I understand, but just change the component to another type and them select kind=component again should keep the same behavior

**Comment by Zaperex** [comment] 2023-11-23 22:50
Oh I think that's because you don't have any owned API entities so it'll then default to all. It'll then keep the all filter when you move back to component.

**Comment by tumido** [comment] 2023-11-24 14:05
Hi @gustavolira, 

This behavior is expected and desired.

Assume your company uses Backstage and the catalog has 10s of thousands of entries in it. You log in to Backstage, go to the catalog page and you will be presented with 10s of thousands of entries. This is not very good UX, since a regular developer is not interested in ALL the components, his attention is focused only on the components he OWNS or he STARRED (aka bookmarked).

In normal cases, guest login wouldn't be even enabled but if it is - Guests don't own any catalog entries. So.. presenting any guest with an empty catalog would be consistent UX, but also wouldn't make much sense... Why present them with an empty screen?

As a result, we have this 2 fold behavior - different for guests where everything is present and focused for logged-in users. 


If you don't mind, I'll close this as not a bug. 🙂

**Closed** 2023-11-24 14:06 UTC
Labels: kind/bug, status/triage, post-FF
